export const floor1Rooms = [
    { name: 'Audio-Visual Room',                                            videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_audiovisualroom.mp4' },
    { name: 'BHive',                                                        videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_bhive.mp4' },
    { name: 'CAD Laboratory',                                               videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_cadlaboratory.mp4' },
    { name: 'CEAFA Lounge',                                                 videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_ceafalounge.mp4' },
    { name: 'Chemistry Laboratory',                                         videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_chemistrylaboratory.mp4' },
    { name: 'ECE Consultation Room',                                        videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_ececonsultationroom.mp4' },
    { name: 'Electronics System Laboratory',                                videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_electronicssystemlaboratory.mp4' },
    { name: 'Executive Lounge',                                             videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_executivelounge.mp4' },
    { name: 'Faculty',                                                      videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_faculty.mp4' },
    { name: 'HVAC Laboratory',                                              videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_hvaclaboratory.mp4' },
    { name: 'Instrumentation and Control Laboratory',                       videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_instrumentationandcontrollaboratory.mp4' },
    { name: 'Mechanical Measurement and Material Testing Laboratory',       videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_mechanicalmeasurementandmaterialtestinglaboratory.mp4' },
    { name: 'Mechatronics and Robotics Laboratory',                         videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_mechatronicsandroboticslaboratory.mp4' },
    { name: 'ME Consultation Room',                                         videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_meconsultationroom.mp4' },
    { name: 'Petroleum Engineering Laboratory',                             videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_petroleumengineeringlaboratory.mp4' },
    { name: 'PFMO',                                                         videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_pfmo.mp4' },
    { name: 'Planning and Development Office',                              videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_planninganddevelopmentoffice.mp4' },
    { name: 'Power Electronics and Mechatronics Education Center',          videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_powerelectronicsandmechatronicseducationcenter.mp4' },
    { name: 'RGO',                                                          videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_rgo.mp4' },
    { name: 'Signal and System Laboratory',                                 videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_signalandsystemlaboratory.mp4' },
    { name: 'University Shop',                                              videoSrc: 'src/assets/CEAFAVideos/1stFloor/ceafa_universityshop.mp4' }
];

export const floor2Rooms = [
    { name: 'Room 207',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_207.mp4' },
    { name: 'Room 208',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_208.mp4' },
    { name: 'Room 209',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_209.mp4' },
    { name: 'Room 210',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_210.mp4' },
    { name: 'Room 211',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_211.mp4' },
    { name: 'Room 212',                     videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_212.mp4' },
    { name: 'COE Staff Office',             videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_coestaffoffice.mp4' },
    { name: 'Conference Room',              videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_conferenceroom.mp4' },
    { name: 'Department Chair Office',      videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_departmentchairoffice.mp4' },
    { name: 'Department Chair Office 2',    videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_departmentchairoffice2.mp4' },
    { name: 'ETEEAP Office',                videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_eteeapoffice.mp4' },
    { name: 'Faculty 1',                    videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_faculty1.mp4' },
    { name: 'Faculty 2',                    videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_faculty2.mp4' },
    { name: 'Faculty 3',                    videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_faculty3.mp4' },
    { name: 'Faculty 4',                    videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_faculty4.mp4' },
    { name: 'Library',                      videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_library.mp4' },
    { name: 'Smart Classroom',              videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_smartclassroom.mp4' },
    { name: 'VCAA Office',                  videoSrc: 'src/assets/CEAFAVideos/2ndFloor/ceafa_vcaaoffice.mp4' }
];

export const floor3Rooms = [
    { name: 'Room 302A',                                videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_302A.mp4' },
    { name: 'Room 302B',                                videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_302B.mp4' },
    { name: 'Room 304',                                 videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_304.mp4' },
    { name: 'Room 305',                                 videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_305.mp4' },
    { name: 'CAFAD Deans Office',                       videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_cafaddeansoffice.mp4' },
    { name: 'CAFAD Faculty Room',                       videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_cafadfacultyroom.mp4' },
    { name: 'COESC',                                    videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_coesc.mp4' },
    { name: 'Computer Laboratory 1',                    videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_computerlaboratory1.mp4' },
    { name: 'Computer Laboratory 2',                    videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_computerlaboratory2.mp4' },
    { name: 'Computer Laboratory 3',                    videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_computerlaboratory3.mp4' },
    { name: 'IE Consultation Laboratory',               videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_ieconsultationlaboratory.mp4' },
    { name: 'Industrial Engineering Laboratory',        videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_industrialengineeringlaboratory.mp4' },
    { name: 'Physics Laboratory',                       videoSrc: 'src/assets/CEAFAVideos/3rdFloor/ceafa_physicslaboratory.mp4' }
];

export const floor4Rooms = [
    { name: 'Room 401',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_401.mp4' },
    { name: 'Room 402',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_402.mp4' },
    { name: 'Room 403',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_403.mp4' },
    { name: 'Room 413',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_413.mp4' },
    { name: 'Room 414',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_414.mp4' },
    { name: 'Room 415',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_415.mp4' },
    { name: 'Room 416',                             videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_416.mp4' },
    { name: 'Amphitheater',                         videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_ampitheater.mp4' },
    { name: 'Analytical Laboratory',                videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_analyticallaboratory.mp4' },
    { name: 'CHE Consultation Room',                videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_checonsultationroom.mp4' },
    { name: 'Chemical Engineering Laboratory',      videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_chemicalengineeringlaboratory.mp4' },
    { name: 'Circuits Laboratory',                  videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_circuitsaboratory.mp4' },
    { name: 'EE Consultation Room',                 videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_eeconsultationroom.mp4' },
    { name: 'EE Supply Room',                       videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_eesupplyroom.mp4' },
    { name: 'Faculty 5',                            videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_faculty5.mp4' },
    { name: 'Food Laboratory',                      videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_foodlaboratory.mp4' },
    { name: 'Instrumentation Laboratory',           videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_instrumentationlaboratory.mp4' },
    { name: 'Machine Laboratory',                   videoSrc: 'src/assets/CEAFAVideos/4thFloor/ceafa_machinelaboratory.mp4' }
];
